'use client';

import '../styles/globals.css'
import { Provider } from 'react-redux'

import { store } from './../app/store';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Provider store={store}>
        {children}
        <ToastContainer 
          position="bottom-right"
          autoClose={5000}
        />
      </Provider>
       </body>
    </html>
  )
}
